# Generated by Django 6.0.5 on 2026-07-15 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='siteconfiguration',
            options={'ordering': ['-updated_at'], 'verbose_name': 'Site Configuration', 'verbose_name_plural': 'Site Configuration'},
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='contact_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='contact_phone',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
