# Generated by Django 6.0.5 on 2026-07-27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("public", "0003_rebrand_reelsdraft")]

    operations = [
        migrations.AddField(
            model_name="siteconfiguration",
            name="twitter_site",
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
