# Generated by Django 6.0.5 on 2026-07-27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0003_cookieconsent"),
    ]

    operations = [
        migrations.AddField(
            model_name="cookieconsent",
            name="anonymous_id",
            field=models.CharField(blank=True, db_index=True, max_length=64),
        ),
        migrations.AddField(
            model_name="cookieconsent",
            name="policy_version",
            field=models.CharField(default="2026-07-21", max_length=32),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="cookieconsent",
            name="purposes",
            field=models.JSONField(default=list),
        ),
    ]
