version: "3.9"

services:
  web:
    build: .
    command: gunicorn core.wsgi:application -c gunicorn.conf.py
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      POSTGRES_HOST: db
      DATABASE_URL: postgres://myniche:myniche@db:5432/myniche
    depends_on:
      - db
      - redis

  db:
    image: postgres:16
    environment:
      POSTGRES_DB: myniche
      POSTGRES_USER: myniche
      POSTGRES_PASSWORD: myniche
    ports:
      - "5432:5432"

  redis:
    image: redis:7
    ports:
      - "6379:6379"
