# Generated by Django 6.0.5 on 2026-07-08 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_google_sub'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='agreed_to_privacy',
            field=models.BooleanField(default=False),
        ),
    ]
