# Generated by Codex on 2026-07-13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_user_agreed_to_privacy"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="main_platform",
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
