# Generated by Django 6.0.5 on 2026-06-11 12:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContentPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('niche', models.CharField(max_length=100)),
                ('platform', models.CharField(max_length=100)),
                ('week_start', models.DateField()),
                ('content_plan', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='content_plans', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PlannedContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_name', models.CharField(max_length=20)),
                ('topic', models.CharField(max_length=255)),
                ('status', models.CharField(default='planned', max_length=30)),
                ('script', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('content_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='planner.contentplan')),
            ],
            options={
                'ordering': ['day_name'],
            },
        ),
    ]
