# Generated by Django 6.0.5 on 2026-07-01 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='plannedcontent',
            name='generated_title',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='plannedcontent',
            name='generated_variant',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
